# Generated by Django 4.1.5 on 2023-01-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mondaiapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Geinin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("neta", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=30)),
                ("importance1", models.FloatField()),
                ("importance2", models.FloatField()),
                ("importance3", models.FloatField()),
                ("importance4", models.FloatField()),
                ("Link", models.URLField()),
            ],
        ),
        migrations.DeleteModel(name="Manzai",),
    ]
