# Generated by Django 4.1.5 on 2023-01-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mondaiapp", "0003_geinin_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geinin", name="image", field=models.TextField(default="タイトル"),
        ),
    ]
