# Generated by Django 4.1.5 on 2023-01-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mondaiapp", "0004_alter_geinin_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="geinin",
            name="description",
            field=models.TextField(default="null"),
        ),
    ]
