# Generated by Django 4.1.5 on 2023-01-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mondaiapp", "0005_geinin_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="geinin", name="importance5", field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name="geinin", name="importance6", field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name="geinin", name="importance1", field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name="geinin", name="importance2", field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name="geinin", name="importance3", field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name="geinin", name="importance4", field=models.FloatField(default=1),
        ),
    ]
